use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fmt::{self, Write};
use std::fs;
use std::path::Path;

const GENERATED_PATH: &str = "crates/mendrel-syntax/src/generated.rs";
const GRAMMAR_PATH: &str = "spec/grammar.ebnf";

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Inventory {
    pub keywords: Vec<String>,
    pub punctuation: Vec<String>,
    pub productions: Vec<String>,
    pub rules: Vec<(String, String)>,
}

#[derive(Debug)]
pub enum GenerateError {
    Io(std::io::Error),
    UnterminatedComment,
    UnterminatedLiteral,
    EmptyInventory,
    UnterminatedProduction,
    GeneratedMismatch,
}

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(formatter, "{error}"),
            Self::UnterminatedComment => formatter.write_str("unterminated EBNF block comment"),
            Self::UnterminatedLiteral => formatter.write_str("unterminated EBNF string literal"),
            Self::EmptyInventory => formatter.write_str("EBNF inventory is empty"),
            Self::UnterminatedProduction => formatter.write_str("unterminated EBNF production"),
            Self::GeneratedMismatch => {
                formatter.write_str("generated syntax inventory is out of date")
            }
        }
    }
}

impl Error for GenerateError {}

impl From<std::io::Error> for GenerateError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

pub fn derive_inventory(grammar: &str) -> Result<Inventory, GenerateError> {
    let grammar = strip_comments(grammar)?;
    let rules = production_rules(&grammar)?;
    let productions = rules.keys().cloned().collect::<Vec<_>>();

    let literals = string_literals(&grammar)?;
    let mut keywords = BTreeSet::new();
    let mut punctuation = BTreeSet::new();
    for literal in literals {
        if literal
            .chars()
            .all(|character| character == '_' || character.is_ascii_alphanumeric())
            && literal
                .chars()
                .next()
                .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        {
            keywords.insert(literal);
        } else {
            punctuation.insert(literal);
        }
    }

    if productions.is_empty() || keywords.is_empty() || punctuation.is_empty() {
        return Err(GenerateError::EmptyInventory);
    }

    Ok(Inventory {
        keywords: keywords.into_iter().collect(),
        punctuation: punctuation.into_iter().collect(),
        productions,
        rules: rules.into_iter().collect(),
    })
}

#[must_use]
pub fn render_inventory(inventory: &Inventory) -> String {
    let mut keywords = inventory.keywords.clone();
    let mut punctuation = inventory.punctuation.clone();
    let mut productions = inventory.productions.clone();
    let mut rules = inventory.rules.clone();
    keywords.sort();
    keywords.dedup();
    punctuation.sort();
    punctuation.dedup();
    productions.sort();
    productions.dedup();
    rules.sort();
    rules.dedup();

    let mut output = String::from(
        "// @generated by `cargo run -p xtask -- generated`; do not edit by hand.\n\n",
    );
    render_string_slice(&mut output, "KEYWORDS", &keywords);
    render_string_slice(&mut output, "PUNCTUATION", &punctuation);
    render_token_metadata(&mut output, &keywords, &punctuation);
    let spaced_operators = punctuation
        .iter()
        .filter(|punctuation| is_spaced_operator(punctuation))
        .cloned()
        .collect::<Vec<_>>();
    render_string_slice(&mut output, "SPACED_OPERATORS", &spaced_operators);
    render_production_rules(&mut output, &rules);
    output.push_str(
        "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]\n\
         pub enum SyntaxKind {\n    Error,\n",
    );
    for production in &productions {
        writeln!(output, "    {},", syntax_variant(production))
            .expect("writing to String cannot fail");
    }
    output.push_str("}\n\nimpl SyntaxKind {\n    #[must_use]\n    pub const fn as_str(self) -> &'static str {\n        match self {\n            Self::Error => \"ERROR\",\n");
    for production in &productions {
        writeln!(
            output,
            "            Self::{} => \"{}\",",
            syntax_variant(production),
            production
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("        }\n    }\n}\n");
    output
}

fn render_token_metadata(output: &mut String, keywords: &[String], punctuation: &[String]) {
    output.push_str(concat!(
        "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n",
        "pub enum TokenClass {\n",
        "    Keyword,\n",
        "    Punctuation,\n",
        "}\n\n",
        "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n",
        "pub struct TokenSpec {\n",
        "    pub text: &'static str,\n",
        "    pub class: TokenClass,\n",
        "    pub stable_id: u64,\n",
        "}\n\n",
        "#[rustfmt::skip]\n",
        "pub const TOKENS: &[TokenSpec] = &[\n",
    ));
    for keyword in keywords {
        writeln!(
            output,
            "    TokenSpec {{ text: {keyword:?}, class: TokenClass::Keyword, stable_id: 0x{:016x} }},",
            stable_token_id(keyword)
        )
        .expect("writing to String cannot fail");
    }
    for punctuation in punctuation {
        writeln!(
            output,
            "    TokenSpec {{ text: {punctuation:?}, class: TokenClass::Punctuation, stable_id: 0x{:016x} }},",
            stable_token_id(punctuation)
        )
        .expect("writing to String cannot fail");
    }
    output.push_str("];\n\n");
}

fn render_production_rules(output: &mut String, rules: &[(String, String)]) {
    output.push_str("#[rustfmt::skip]\npub const PRODUCTION_RULES: &[(&str, &str)] = &[\n");
    for (name, rule) in rules {
        writeln!(output, "    ({name:?}, {rule:?}),").expect("writing to String cannot fail");
    }
    output.push_str(concat!(
        "];\n\n",
        "#[must_use]\n",
        "pub fn production_rule(name: &str) -> Option<&'static str> {\n",
        "    PRODUCTION_RULES\n",
        "        .binary_search_by(|(production, _)| production.cmp(&name))\n",
        "        .ok()\n",
        "        .map(|index| PRODUCTION_RULES[index].1)\n",
        "}\n\n",
    ));
}

fn stable_token_id(text: &str) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325_u64;
    for byte in text.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    hash
}

fn is_spaced_operator(text: &str) -> bool {
    text != "!"
        && text != "?"
        && text.chars().all(|character| {
            matches!(
                character,
                '!' | '%' | '&' | '*' | '+' | '-' | '/' | '<' | '=' | '>' | '^' | '|'
            )
        })
}

pub fn check_inventory(root: &Path) -> Result<(), GenerateError> {
    let expected = expected_inventory(root)?;
    let actual = fs::read_to_string(root.join(GENERATED_PATH))?;
    if actual == expected {
        Ok(())
    } else {
        Err(GenerateError::GeneratedMismatch)
    }
}

pub fn write_inventory(root: &Path) -> Result<(), GenerateError> {
    let expected = expected_inventory(root)?;
    fs::write(root.join(GENERATED_PATH), expected)?;
    Ok(())
}

fn expected_inventory(root: &Path) -> Result<String, GenerateError> {
    let grammar = fs::read_to_string(root.join(GRAMMAR_PATH))?;
    derive_inventory(&grammar).map(|inventory| render_inventory(&inventory))
}

fn render_string_slice(output: &mut String, name: &str, values: &[String]) {
    writeln!(output, "#[rustfmt::skip]\npub const {name}: &[&str] = &[")
        .expect("writing to String cannot fail");
    for value in values {
        writeln!(output, "    {value:?},").expect("writing to String cannot fail");
    }
    output.push_str("];\n\n");
}

fn syntax_variant(production: &str) -> String {
    let mut result = String::new();
    for word in production.split('_') {
        let mut characters = word.chars();
        if let Some(first) = characters.next() {
            result.extend(first.to_uppercase());
            result.extend(characters);
        }
    }
    result
}

fn production_rules(grammar: &str) -> Result<BTreeMap<String, String>, GenerateError> {
    let mut rules = BTreeMap::new();
    let mut cursor = 0;
    while cursor < grammar.len() {
        cursor += grammar[cursor..]
            .find(|character: char| !character.is_whitespace())
            .unwrap_or(grammar.len() - cursor);
        if cursor == grammar.len() {
            break;
        }

        let name_start = cursor;
        while grammar
            .as_bytes()
            .get(cursor)
            .is_some_and(|byte| *byte == b'_' || byte.is_ascii_lowercase() || byte.is_ascii_digit())
        {
            cursor += 1;
        }
        if cursor == name_start {
            cursor += grammar[cursor..]
                .chars()
                .next()
                .expect("cursor is before end of grammar")
                .len_utf8();
            continue;
        }
        let name = &grammar[name_start..cursor];
        while grammar
            .as_bytes()
            .get(cursor)
            .is_some_and(u8::is_ascii_whitespace)
        {
            cursor += 1;
        }
        if grammar.as_bytes().get(cursor) != Some(&b'=') {
            continue;
        }
        cursor += 1;
        let rule_start = cursor;
        let mut in_literal = false;
        let mut escaped = false;
        let mut rule_end = None;
        for (relative, character) in grammar[cursor..].char_indices() {
            if in_literal {
                if escaped {
                    escaped = false;
                } else if character == '\\' {
                    escaped = true;
                } else if character == '"' {
                    in_literal = false;
                }
            } else if character == '"' {
                in_literal = true;
            } else if character == ';' {
                rule_end = Some(cursor + relative);
                break;
            }
        }
        let Some(rule_end) = rule_end else {
            return Err(GenerateError::UnterminatedProduction);
        };
        let normalized = grammar[rule_start..rule_end]
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        rules.insert(name.to_owned(), normalized);
        cursor = rule_end + 1;
    }
    Ok(rules)
}

fn strip_comments(grammar: &str) -> Result<String, GenerateError> {
    let bytes = grammar.as_bytes();
    let mut output = String::with_capacity(grammar.len());
    let mut index = 0;
    let mut depth = 0_u32;
    while index < bytes.len() {
        if bytes[index..].starts_with(b"(*") {
            depth += 1;
            index += 2;
        } else if bytes[index..].starts_with(b"*)") && depth > 0 {
            depth -= 1;
            index += 2;
        } else {
            if depth == 0 {
                output.push(char::from(bytes[index]));
            } else if bytes[index] == b'\n' {
                output.push('\n');
            }
            index += 1;
        }
    }
    if depth == 0 {
        Ok(output)
    } else {
        Err(GenerateError::UnterminatedComment)
    }
}

fn string_literals(grammar: &str) -> Result<BTreeSet<String>, GenerateError> {
    let mut literals = BTreeSet::new();
    let mut characters = grammar.chars().peekable();
    while let Some(character) = characters.next() {
        if character != '"' {
            continue;
        }
        let mut literal = String::new();
        let mut closed = false;
        while let Some(character) = characters.next() {
            match character {
                '"' => {
                    closed = true;
                    break;
                }
                '\\' => {
                    let escaped = characters
                        .next()
                        .ok_or(GenerateError::UnterminatedLiteral)?;
                    literal.push(escaped);
                }
                character => literal.push(character),
            }
        }
        if !closed {
            return Err(GenerateError::UnterminatedLiteral);
        }
        literals.insert(literal);
    }
    Ok(literals)
}
